version: "3.9"

services:
  backend:
    build: ./backend
    container_name: escola_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-local
      - ALLOWED_HOSTS=*
      - DB_NAME=escola_db
      - DB_USER=escola_user
      - DB_PASSWORD=escola_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: escola_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: escola_db
    restart: always
    environment:
      POSTGRES_DB: escola_db
      POSTGRES_USER: escola_user
      POSTGRES_PASSWORD: escola_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: