# Generated by Django 6.0.3 on 2026-03-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
        ('users', '0003_user_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='turmas.turma'),
        ),
    ]
